### ISSUE TITLE
Surveys

### ISSUE THREAD

**Issue by finnss** [webkom/lego-webapp#986]
Add surveys to Abakus.no, giving us a way to gather feedback after events.

Requires https://github.com/webkom/lego/pull/525. 

I'm using this PR to track progress across pull requests.

- [x] Actions to fetch, add, edit, and delete surveys. (#901)
- [x] Reducer for surveys including selectors and EntityTypes. (#901)
- [x] Routes and components for list view, detail view, editing, and adding surveys. (#901)
- [x] All necessary intermediate files such as the `index.js` making the feature available at  `/surveys/`. (#901)
- [x] Components to render actual forms: Question, Answer, and Option.
- [x] Using those components in detail view, and making them editable and sendable in `SurveyEditor`.
- [x] Actions, Routes, and components for adding Submissions, so that forms can actually be answered.
- [x] Actions, Routes, and components for viewing Submissions, so that those answers can be read.
- [x] Making surveys from templates 
- [ ] Generating graphs or charts or some such to make viewing Submissions manageable. 
- [x] Functionality for sending mails to attendees of an event with link to the Survey
- [x] Tie surveys closer with events somehow. At least a link for the event admins to make a survey from an event page, which means I also need functionality to pass an event to the "add survey" page.
